---  
  - hosts: apic
    vars:
      aci_login: &aci_login
        host: 172.16.255.10
        username: api_user
        private_key: /home/student/CAB19-SJC/fabric_dmz_api_user.key
        certificate_name: api_user_cert
        use_proxy: no
        validate_certs: no
      contracts:
        webapp:
          ctrt: Webapp_ctrt
          filter: webapp_filter
          port: http
        db:
          ctrt: DB_ctrt
          filter: db_filter
          port: 3306

    tasks:
    - name: Register new leaf node
      aci_rest:
        <<: *aci_login
        path: /api/node/mo/uni/controller/nodeidentpol.json
        method: post
        content:
          fabricNodeIdentP:
            attributes:
              name: "{{ node_name }}"
              role: "leaf"
              serial: "{{ node_serial }}"
              nodeId: "{{ node_id | string }}"
    - name: Deploy Tenant
      aci_tenant:
        <<: *aci_login 
        tenant: "{{ tenant }}"
    - name: Create Filters
      aci_filter:
        <<: *aci_login 
        name: "{{ item }}"
        tenant: "{{ tenant }}"
      with_items:
        - webapp_filter
        - db_filter
    - name: Create Filter Entries
      aci_filter_entry:
        <<: *aci_login
        name: "{{ item.value.ctrt }}"
        ether_type: ip
        ip_protocol: tcp
        tenant: "{{ tenant }}"
        filter: "{{ item.value.filter }}"
        dst_port: "{{ item.value.port }}"
      with_dict: "{{ contracts }}"
    - name: Create Contracts
      aci_contract:
        <<: *aci_login
        name: "{{ item }}"
        tenant: "{{ tenant }}"
      with_items:
        - Webapp_ctrt
        - DB_ctrt
    - name: Create Subjects
      aci_contract_subject:
        <<: *aci_login
        name: "subject"
        contract: "{{ item.value.ctrt }}"
        tenant: "{{ tenant }}"
      with_dict: "{{ contracts }}"
    - name: Associate filter to subject
      aci_contract_subject_to_filter:
        <<: *aci_login
        tenant: "{{ tenant }}"
        contract: "{{ item.value.ctrt }}"
        subject: "subject"
        filter: "{{ item.value.filter }}"
      with_dict: "{{ contracts }}"
    - name: Deploy VRF
      aci_vrf:
        <<: *aci_login
        vrf: ctx_01
        tenant: "{{ tenant }}"
    - name: Deploy BD
      aci_bd:
        <<: *aci_login
        tenant: "{{ tenant }}"
        bd: bd_01
        vrf: ctx_01
    - name: Deploy Application Profile
      aci_ap:
        <<: *aci_login
        tenant: "{{ tenant }}"
        ap: myApp
    - name: Deploy EPG Web
      aci_epg:
        <<: *aci_login
        tenant: "{{tenant }}"
        bd: bd_01
        ap: myApp
        epg: Web
    - name: Deploy EPG App
      aci_epg:
        <<: *aci_login
        tenant: "{{ tenant }}"
        bd: bd_01
        ap: myApp
        epg: App
    - name: Deploy EPG DB
      aci_epg:
        <<: *aci_login
        tenant: "{{ tenant }}"
        bd: bd_01
        ap: myApp
        epg: DB
    - name: Deploy VMware Web Portgroup
      aci_epg_to_domain:
        <<: *aci_login
        tenant: "{{ tenant }}"
        ap: myApp
        epg: Web
        domain: VMM-VDS-DMZ-01
        domain_type: vmm
        vm_provider: vmware
    - name: Deploy VMware App Portgroup
      aci_epg_to_domain:
        <<: *aci_login
        tenant: "{{ tenant }}"
        ap: myApp
        epg: App
        domain: VMM-VDS-DMZ-01
        domain_type: vmm
        vm_provider: vmware
    - name: Deploy VMware DB Portgroup
      aci_epg_to_domain:
        <<: *aci_login
        tenant: "{{ tenant }}"
        ap: myApp
        epg: DB
        domain: VMM-VDS-DMZ-01
        domain_type: vmm
        vm_provider: vmware
    - name: Associate DB provider contracts
      aci_epg_to_contract:
        <<: *aci_login
        tenant: "{{ tenant }}"
        ap: myApp
        epg: DB
        contract: DB_ctrt
        contract_type: provider
    - name: Associate App provider contracts
      aci_epg_to_contract:
        <<: *aci_login
        tenant: "{{ tenant }}"
        ap: myApp
        epg: App
        contract: Webapp_ctrt
        contract_type: provider
    - name: Associate App consumer contracts
      aci_epg_to_contract:
        <<: *aci_login
        tenant: "{{ tenant }}"
        ap: myApp
        epg: App
        contract: DB_ctrt
        contract_type: consumer
    - name: Associate Web consumer contracts
      aci_epg_to_contract:
        <<: *aci_login
        tenant: "{{ tenant }}"
        ap: myApp
        epg: Web
        contract: Webapp_ctrt
        contract_type: consumer
    - name: Get fabric topology
      aci_fabric_node:  
        <<: *aci_login
        state: query
      register: json_response
    - name: Parse fabric nodes
      set_fact:
        nodes: "{{ 'Node ' + item.fabricNodeIdentP.attributes.name + ' has serial: ' + item.fabricNodeIdentP.attributes.serial}}"
      with_items: "{{ json_response.current }}"
      register: nodes_json
    - name: Create list of nodes
      set_fact:
        nodes: "{{ nodes_json.results | map(attribute='ansible_facts.nodes') | list }}"
    - name: Print nodes
      debug: var=nodes
      